from . import account_move
from . import account_move_line
from . import sale_order_line
from . import sale_order
from . import res_partner
from . import factures_delivery_routes_generation
from . import factures_delivery_routes
from . import factures_salesperson_routes
from . import factures_salesperson_history
from . import res_users
from . import account_journal